apiVersion: minio.scc-digitalhub.github.io/v1
kind: Policy
metadata:
  labels:
    app.kubernetes.io/name: policy
    app.kubernetes.io/instance: policy-sample
    app.kubernetes.io/part-of: minio-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: minio-operator
  name: policy-sample
spec:
  # TODO(user): Add fields here
